### ISSUE TITLE
Torq consuming lot of CPU with large database

### ISSUE THREAD

**Issue by maxwedwards** [lncapital/torq#139]
Torq consuming lot of CPU with large database

**Comment by ohenrik** [comment]
context: 
https://t.me/c/1697263950/1411

https://t.me/c/1697263950/1688

**Comment by ohenrik** [comment]
Can we mark this as completed?

**Comment by 2Fast2BCn** [comment]
We discovered a new problem. It has been addressed but we still need to finalize testing. We expect to release this new version next week! As a temporary fix you could periodically reboot Torq until we release v0.20.x
Sorry for this inconvenience!
