### ISSUE TITLE
Add columns to Channels page

### ISSUE THREAD

**Issue by ohenrik** [lncapital/torq#167]
Add:
* Peer alias of channel (e.g. channel 2344x92x123 belongs to the peer "allnice"
* Add local node name (currently the same as in settings, which is the connection IP details)
* Link to Channel page on Mempool
* Link to Channel page on Amboss
* Link to Channel page on 1ml.com

Change
* Gauge needs a new cell type that is more descriptive. (Will post design here shortly). The gauge should also be formatted as percent.
* Columns "Status" should be renamed to "Active" (It shows if the channel is active or paused)
* Pending HTLCs is currently showing the unsettled balance and not the count of HTLCs.

**Comment by kevenboo** [comment]
- The Local name part was done with the ticket https://github.com/lncapital/torq/issues/154
