### ISSUE TITLE
Channel ID missing from event history list

### ISSUE THREAD

**Issue by ohenrik** [lncapital/torq#186]
Channel ID should be visible over each new daily list of events. Currently only a pipe is visible. This is most likely due to the change from channelId to shortChannelId key name.

![Screenshot 2022-10-26 at 12 26 25](https://user-images.githubusercontent.com/647617/198003255-a5ba99eb-dddf-45ad-9a7c-12cb0d140b9b.png)

**Comment by kevenboo** [comment]
This is fixed on the PR -> https://github.com/lncapital/torq/issues/137
