### ISSUE TITLE
Adding a second LND node doesn't work

### ISSUE THREAD

**Issue by feelancer21** [lncapital/torq#262]
Version: 0.15.2

I wanted to a second node to my test environment, but I receive the message, that the node already exists. Attached some screenshots about the new node and the existing node.

![image](https://user-images.githubusercontent.com/2828397/207661042-4d50cd82-d954-4494-a957-d0dfae11f14e.png)
![image](https://user-images.githubusercontent.com/2828397/207661103-81b6645b-6ba9-4b84-bb88-7a23c0a12915.png)
![image](https://user-images.githubusercontent.com/2828397/207661243-1b392a23-4423-483d-97d4-67b6be1ed9fd.png)

**Comment by 2Fast2BCn** [comment]
Would it be possible that you deleted a node with the same public key and then tried to add it again? Just trying to find a reproducible test case.

**Comment by 2Fast2BCn** [comment]
Thanks for reporting!!!

**Comment by feelancer21** [comment]
Even deleting and adding the same node is not possible.

**Comment by 2Fast2BCn** [comment]
That should be fixed too once the PR is merged in.
