### ISSUE TITLE
Adding node with incorrect url does not return an error to the user

### ISSUE THREAD

**Issue by ohenrik** [lncapital/torq#275]
After adding a node with the wrong URL there is no UI info that it cannot connect, just the CLI output

**Comment by kevenboo** [comment]
I think We can close this one I got errors with wrong urls
<img width="429" alt="Screenshot 2023-01-27 at 6 04 20 PM" src="https://user-images.githubusercontent.com/84108679/215161423-227378c3-84f1-43db-85bc-2e48c25b53ec.png">

**Comment by maxwedwards** [comment]
Closing as fixed
