### ISSUE TITLE
go mod vendor fails

### ISSUE THREAD

**Issue by prusnak** [lncapital/torq#320]
We are trying to package torq to Nixpkgs and Nix-Bitcoin - see https://github.com/fort-nix/nix-bitcoin/issues/581

`go build` works fine, but running `go mod vendor` shows the following error:

```
go: downloading go.opentelemetry.io/otel/internal/metric v0.27.0
github.com/lncapital/torq/pkg/lnd_connect imports
        github.com/lightningnetwork/lnd/macaroons imports
        github.com/lightningnetwork/lnd/kvdb imports
        github.com/lightningnetwork/lnd/kvdb/etcd imports
        go.etcd.io/etcd/server/v3/embed imports
        go.opentelemetry.io/otel/semconv: no required module provides package go.opentelemetry.io/otel/semconv; to add it:
        go get go.opentelemetry.io/otel/semconv
github.com/lncapital/torq/pkg/lnd_connect imports
        github.com/lightningnetwork/lnd/macaroons imports
        github.com/lightningnetwork/lnd/kvdb imports
        github.com/lightningnetwork/lnd/kvdb/etcd imports
        go.etcd.io/etcd/server/v3/embed imports
        go.opentelemetry.io/otel/exporters/otlp imports
        go.opentelemetry.io/otel/sdk/metric/controller/basic imports
        go.opentelemetry.io/otel/metric/registry: no required module provides package go.opentelemetry.io/otel/metric/registry; to add it:
        go get go.opentelemetry.io/otel/metric/registry
```

Any ideas what might be causing this and what is the fix?

**Comment by ohenrik** [comment]
Did you try to run `go get go.opentelemetry.io/otel/semconv/v1.4.0`?  I have never tried to vendor Torq, but let me know if the command does not work and I can dig deeper

**Comment by ohenrik** [comment]
I'm trying a fix now, running the e2e tests to see if there are any build problems.

**Comment by mmilata** [comment]
With 9d02ce05e8bdaf77c9eded5f1833175d72846514 `go mod vendor` (used by nixpkg internally) complains about missing go.sum entry for `go.opentelemetry.io/otel/exporters/trace/jaeger@v0.20.0`. After adding it the same error as in OP is produced.

**Comment by ohenrik** [comment]
Hmmmmm, I don't have a lot of experience with go mod vendor. What are you trying to do? Why do you need to vendor?

**Comment by ohenrik** [comment]
Could you try running `go clean -modcache` and then use this branch: 

`https://github.com/lncapital/torq/tree/etcd-upgrade`

**Comment by ohenrik** [comment]
I merged the fix into main now.

**Comment by mmilata** [comment]
Fixed the problem on my end, thank you very much!

**Comment by prusnak** [comment]
Thanks for the fix. Closing. If we hit some other issues with vendoring we'll open a new issue.
