### ISSUE TITLE
Add instructions how to bake a macaroon with required permissions

### ISSUE THREAD

**Issue by prusnak** [lncapital/torq#333]
Advanced admins don't use `admin.macaroon` for everything.

They bake macaroons according to which permissions are required.

Having a line similar to this one in the docs helps tremendously, since it is then obvious which permissions are required:

```
lncli bakemacaroon --save_to=torq.macaroon info:read invoices:read invoices:write offchain:read offchain:write
```

**Comment by 2Fast2BCn** [comment]
That's a very good point. We should add that for sure!

**Comment by ohenrik** [comment]
Thank you for the feedback @prusnak , this is now added to the readme 🎉
