### ISSUE TITLE
Embed web/build subfolder via go:embed into the final binary

### ISSUE THREAD

**Issue by prusnak** [lncapital/torq#395]
This allows Torq to be distributed as a single binary simplifying deployment significantly.

**Comment by ohenrik** [comment]
We'll try to add this soon, thank you for adding the issue :) We should probably also create a go binary release as an alternative to the docker image.

**Comment by prusnak** [comment]
> We'll try to add this soon, thank you for adding the issue

Yeah, I remember you mentioning it on our call. I just wanted to make an issue, so this idea is not forgotten.

**Comment by maxwedwards** [comment]
Work is complete, next Torq release will have frontend embedded

**Comment by prusnak** [comment]
cc @mmilata
