### ISSUE TITLE
[Automation] Add Channel Filter “Number of updates”

### ISSUE THREAD

**Issue by itmanagerro** [lncapital/torq#453]
Short description: “Number of channel state updates"

Long Description: “Number of updates the channel has accrued since it’s genesis”

Requires: #455

Related: https://github.com/lightningnetwork/lnd/issues/5705#issuecomment-954617919

Use cases:
Tag “Clogged” channels `if $number_of_updates > 100000, tag channel as ‘Clogged’` (maybe some sort of echo “Consider close and reopen...")

**Comment by ohenrik** [comment]
Great feature request! Thank you!

**Comment by 2Fast2BCn** [comment]
Done. Will be in the next major release.
