### ISSUE TITLE
[Tags] Add Tag “Clogged”

### ISSUE THREAD

**Issue by itmanagerro** [lncapital/torq#455]
Description: Tag for dead channels (not used for NN days)

Requires: #454

Use cases:
Tag “Clogged” channels `if $number_of_updates > 100000, tag channel as ‘Clogged’` (maybe some sort of echo “Consider close and reopen...")

**Comment by ohenrik** [comment]
Thank you. You can create your own Tags (like "dead" and "dormant"), but we are missing the last_fwd_delta variable. So I'll close these Tag related feature request and keep the https://github.com/lncapital/torq/issues/453 and #454 issues open.
