### ISSUE TITLE
[Tags] Add Tag “Dead”

### ISSUE THREAD

**Issue by itmanagerro** [lncapital/torq#458]
Description: Tag for dead channels (not used for NNN days)

Requires: #454

Use cases:
Tag “Dead” channels `if $last_fwd_delta > 365 days, tag channel as ‘Dead’`

**Comment by ohenrik** [comment]
Thank you. You can create your own Tags (like "dead" and "dormant"), but we are missing the `last_fwd_delta` variable. So I'll close these Tag related feature request and keep the #453 issue open.
