### ISSUE TITLE
Node duplication when attempting to add a node tag.

### ISSUE THREAD

**Issue by 2Fast2BCn** [lncapital/torq#475]
![image](https://user-images.githubusercontent.com/4680358/221814309-595480d0-299a-4062-989c-88f746e8d0c2.png)

**Comment by 2Fast2BCn** [comment]
This happens when you have several channels with the same peer.

**Comment by maxwedwards** [comment]
Also I have channel duplication:

![Image](https://user-images.githubusercontent.com/1204616/232024215-23788704-45f0-4878-8c1a-1dc4d3c831a8.png)

I do not have more than one channel with the same peer but I do have a deleted node.
