### ISSUE TITLE
Running torq section in contributing guidelines is not comprehensive

### ISSUE THREAD

**Issue by Jhoyola** [lncapital/torq#577]
I tried to run the dev env of torq following CONTRIBUTING.md.

When running this part:
_Once the command successfully finished the command to start torq will be visible and will look something like go run ./cmd/torq/torq.go --torq.password password --db.name torq --db.port 5432 --db.password password start_
I got a GO error: _web\web.go:16:12: pattern build: no matching files found_
It seems I needed to run _npm run build_ first to create the build dir into /web. This was missing from CONTRIBUTING.md

Secondly neither commands to run worked:
- From CONTRIBUTING.md: _go run ./cmd/torq/torq.go --torq.password password --db.name torq --db.port 5432 --db.password password start_
- Nor from the output of virtual network creation: _go build ./cmd/torq && ./torq --torq.password password --db.user postgres --db.port 5444 --db.password password start_

What worked was the first command but the port needed to be replaced with 5444.

I can make a pull request fixing these. Or is there something I have misunderstood?

**Comment by ohenrik** [comment]
Thank you for submitting the issue @Jhoyola. We would really appreciate a PR for this.

**Comment by Jhoyola** [comment]
Nice, I will.

Off topic: I would like to start contributing to interesting Bitcoin projects and torq seems very interesting one. Could you suggest which issue would be best one to start with, out of the current ones?
