### ISSUE TITLE
Help needed with using Torq please:

### ISSUE THREAD

**Issue by BonzoDogDooDah** [lncapital/torq#6]
Hello,

We have tried in the past to use Torq to automatically rebalance some of our channels but were unsucessful :(

Is there a step by step tutorial on how to set up Torq to auto rebalance as we may have missed something the 1st time?

We are thinking that we should start over from scratch? 

We are not quite newbie's and have aquired some skills.

We are using the Torq app from Umbrel on a Rpi 4.

Thank you.

**Comment by Tobben67** [comment]
LNDg > Torq (when it comes to rebalancing)?

Only the best regards

**Comment by 2Fast2BCn** [comment]
`v1.5.0` has some rebalancer optimizations.
I'm obviously biased but if you want fine control on rebalancing then Torq is the only available option with a UI.

Here is a video about our automations (including a rebalancer) https://www.youtube.com/watch?v=Go4uJoMhwrE
