### ISSUE TITLE
Filters for tags need to be altered due to peersTags/channelsTags columns change (also for automation).

### ISSUE THREAD

**Issue by ohenrik** [lncapital/torq#655]
Channel filters needs to be updated to use channelTags and peerTags instead of just tags. Right now filtering on tags does not work at all.

There are two ways to solve this. 
1. Add a migration to transfer filters over to filter on both peerTags and channelTags columns with the same tags.
2. Create a virtual filterable column that filters on both of these and not just one of them (in addition to the peer and channel specific columns). This would perhaps also be more convenient to the user.

![Image](https://user-images.githubusercontent.com/647617/236151880-ff4189a9-4fe7-465d-900a-e11bec188120.png)

We might need to

**Comment by maxwedwards** [comment]
Opting for option 2
