### ISSUE TITLE
No migration found when starting Torq from binary

### ISSUE THREAD

**Issue by yo-mr-white** [lncapital/torq#9]
I installed latest version (1.5.1) from binary (linux-arm64). When I want to start it (``./torq-core -c .torq.conf start``), it successfully connects to the DB, but then I got this error:

```
{"level":"info","time":"2024-02-04T16:56:16+01:00","message":"Migrations might take a while. Please be patient."}
{"level":"error","error":"Running up migration: no migration found for version 0: read down for version 0 .: file does not exist","time":"2024-02-04T16:56:16+01:00","message":"Torq could not migrate the database."}
{"level":"debug","time":"2024-02-04T16:56:16+01:00","message":"RootService cancellation requested"}
{"level":"debug","time":"2024-02-04T16:56:16+01:00","message":"RootService updating current state to Inactive (due to failure)"}
{"level":"debug","time":"2024-02-04T16:56:16+01:00","message":"Cancel function called."}
{"level":"info","time":"2024-02-04T16:56:17+01:00","message":"Torq is dead."}
```

Any ideas how to solve it?

**Comment by 2Fast2BCn** [comment]
Are you sure the file `.torq.conf` is readable and in the same folder as the binary you are running?
It's not a typo? `./torq-core -c ./torq.conf start`

**Comment by yo-mr-white** [comment]
Yes, I am sure. The name and also access rights are correct. If I change the DB password in config file to something else, then I am getting different error, that the Torq couldn't connect to the DB, so there is no problem with reading the config file.

**Comment by 2Fast2BCn** [comment]
OK, thank you for reporting this. We will have to look into it. Potentially there was a problem including the migration files in the binary.

**Comment by 2Fast2BCn** [comment]
You should also have logs from the timescaledb right? No extra clues in there?

**Comment by tinova** [comment]
Same issue here, starting from scratch, with a vanilla and empty postgresql, on a raspbian.

**Comment by 2Fast2BCn** [comment]
Postgresql will not work, you need timescaledb. If it's also not working for timescaledb could you check timescaledb logs for me please.
